version: '3'

services:
  liquibase:
    container_name: "liquibase-update"
    image: liquibase-update
    build:
      context: "./"
      dockerfile: "Dockerfile"
    networks:
      - spring-net

networks:
  spring-net:
    external: true